### PR TITLE
Improve the compilation process

### PR DESCRIPTION
**Pull request by lnsyyj**
1. Add build dependency script
2. Add fio to gitmodules

Signed-off-by: JiangYu <lnsyyj@hotmail.com>

### CODE REVIEW

**Comment by vitalif** [comment]
Sorry, please don't add fio into gitmodules, because the exact version for each distribution has to be symlinked/copied there during package build

**Comment by lnsyyj** [comment]
ok, i will remove fio.

**Comment by lnsyyj** [comment]
Hi @vitalif ,
Will there be version management in this regard in the future?
I want to find a suitable version management method so that the project can move forward better.

**Comment by vitalif** [comment]
What do you mean by that? :-)
Vitastor has to be built with fio from the distribution, otherwise it won't work, and fio still doesn't have proper support for building out-of-tree modules - i.e. development headers, something like "fio-dev" package.
Regarding packages: have you seen containerized package build scripts in debian/ and rpm/?)
You can build rpm/deb packages with 1 bash script, you just need podman installed. :-)

**Comment by lnsyyj** [comment]
Oh thanks, I just saw that.

**Pull request closed without merging**
